[package]
name = "z_order_offsetting"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "*"
morton-encoding = "*"
bit-set = "0.5.3"